nombre = input("ingrese su nombre :")
apellido = input("Ingrese su apellido :")
rut = input("Ingrese su RUT: ")
duoc_mail = input("Ingrese su correo electronico Duoc :")
duoc_sede = input("Ingrese la sede de Duoc a la cual pertenece :")
print("\nDatos ingresados:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("RUT:", rut)
print("Correo :", duoc_mail)
print("Sede duoc", duoc_sede)
